# Generated by Django 5.2.17 on 2026-10-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('succeeded', 'Выполнен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='queued', max_length=16)),
                ('trigger', models.CharField(choices=[('manual', 'Кнопка'), ('import', 'После импорта'), ('command', 'Команда')], max_length=16)),
                ('scope', models.CharField(choices=[('all', 'Все товары без категории'), ('products', 'Выбранные товары')], max_length=16)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('requested_count', models.PositiveIntegerField(default=0)),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('unknown_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('remaining_count', models.PositiveIntegerField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('run_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('recoveries', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('schema_version', models.CharField(blank=True, default='', max_length=64)),
                ('classifier_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'id'], name='classification_run_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'queued')), fields=('status',), name='classification_run_one_queued'), models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='classification_run_one_running'), models.CheckConstraint(condition=models.Q(models.Q(('heartbeat_at__isnull', False), ('lease_expires_at__isnull', False), ('run_token__isnull', False), ('status', 'running')), models.Q(models.Q(('status', 'running'), _negated=True), ('heartbeat_at__isnull', True), ('lease_expires_at__isnull', True), ('run_token__isnull', True)), _connector='OR'), name='classification_run_ownership_check'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', False), ('status__in', ['succeeded', 'failed', 'cancelled'])), models.Q(('finished_at__isnull', True), ('status__in', ['queued', 'running'])), _connector='OR'), name='classification_run_finished_check')],
            },
        ),
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('superseded', 'Заменено')], default='pending', max_length=16)),
                ('resolution', models.CharField(blank=True, choices=[('confirmed', 'Подтверждено'), ('other', 'Выбран другой'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено командой'), ('changed', 'Изменено вне экрана'), ('merged', 'Товар поглощён слиянием'), ('product_removed', 'Товар удалён')], default='', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('product_ref', models.BigIntegerField()),
                ('origin_product_ref', models.BigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_facts', models.JSONField(blank=True, default=dict)),
                ('previous_generic_ref', models.BigIntegerField()),
                ('previous_generic_name', models.CharField(max_length=100)),
                ('previous_generic_base_unit', models.CharField(max_length=8)),
                ('suggested_generic_ref', models.BigIntegerField()),
                ('suggested_generic_name', models.CharField(max_length=100)),
                ('suggested_base_unit', models.CharField(max_length=8)),
                ('suggested_category_path', models.JSONField(blank=True, default=list)),
                ('final_generic_ref', models.BigIntegerField(blank=True, null=True)),
                ('final_generic_name', models.CharField(blank=True, default='', max_length=100)),
                ('final_base_unit', models.CharField(blank=True, default='', max_length=8)),
                ('classifier_version', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=64)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('active_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_classification', to='catalog.product')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='classification.classificationrun')),
                ('suggested_generic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.genericproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_key', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to='classification.productclassification')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.PositiveIntegerField()),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('succeeded', 'Выполнена'), ('failed', 'Ошибка')], default='running', max_length=16)),
                ('input_sha256', models.CharField(max_length=64)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('invalid_output_text', models.TextField(blank=True, default='', max_length=65536)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classification.classificationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'batch', 'ordinal'), name='classification_attempt_run_batch_ordinal_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CreatedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_ref', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('parent_ref', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('provisional', 'Новая'), ('kept', 'Принята'), ('removed', 'Удалена')], default='provisional', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_origin', to='catalog.category')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to='classification.classificationrun')),
            ],
            options={
                'verbose_name_plural': 'created categories',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('state', 'provisional')), models.Q(('resolved_at__isnull', False), ('state__in', ['kept', 'removed'])), _connector='OR'), name='classification_created_category_state_check')],
            },
        ),
        migrations.CreateModel(
            name='CreatedGenericProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_ref', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('base_unit', models.CharField(max_length=8)),
                ('category_ref', models.BigIntegerField()),
                ('state', models.CharField(choices=[('provisional', 'Новая'), ('kept', 'Принята'), ('removed', 'Удалена')], default='provisional', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('generic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_origin', to='catalog.genericproduct')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_generics', to='classification.classificationrun')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('state', 'provisional')), models.Q(('resolved_at__isnull', False), ('state__in', ['kept', 'removed'])), _connector='OR'), name='classification_created_generic_state_check')],
            },
        ),
        migrations.AddIndex(
            model_name='productclassification',
            index=models.Index(fields=['status', 'suggested_generic_name', 'suggested_generic_ref', 'id'], name='classification_rec_screen_idx'),
        ),
        migrations.AddIndex(
            model_name='productclassification',
            index=models.Index(fields=['product_ref', 'id'], name='classification_rec_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productclassification',
            index=models.Index(fields=['suggested_generic_ref', 'status'], name='classification_rec_generic_idx'),
        ),
        migrations.AddConstraint(
            model_name='productclassification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution', ''), ('resolved_at__isnull', True), ('status', 'pending')), models.Q(('resolved_at__isnull', False), ('status__in', ['confirmed', 'rejected', 'superseded']), models.Q(('resolution', ''), _negated=True)), _connector='OR'), name='classification_record_pending_unresolved'),
        ),
        migrations.AddConstraint(
            model_name='productclassification',
            constraint=models.CheckConstraint(condition=models.Q(('active_product__isnull', True), ('status', 'pending'), _connector='OR'), name='classification_record_active_pending'),
        ),
        migrations.AddConstraint(
            model_name='classificationrejection',
            constraint=models.UniqueConstraint(fields=('product', 'generic_key'), name='classification_rejection_product_key_uniq'),
        ),
    ]
