# Generated by Django 5.2.17 on 2026-10-03 12:25

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_brand_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='GenericProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_unit', models.CharField(choices=[('kg', 'кг'), ('l', 'л'), ('pcs', 'шт')], max_length=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generic_products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('gtin', models.CharField(blank=True, default='', max_length=14)),
                ('package_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('package_unit', models.CharField(blank=True, choices=[('pcs', 'шт'), ('g', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л'), ('m', 'м')], default='', max_length=8)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.genericproduct')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='catalog_category_parent_name_uniq', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='genericproduct',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_genericproduct_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('gtin', ''), _negated=True), fields=('gtin',), name='catalog_product_gtin_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'name', 'package_quantity', 'package_unit'), name='catalog_product_brand_name_package_uniq', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('package_quantity__isnull', True), ('package_unit', '')), models.Q(('package_quantity__isnull', False), models.Q(('package_unit', ''), _negated=True)), _connector='OR'), name='catalog_product_package_both_or_none'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('package_quantity__isnull', True), ('package_quantity__gt', 0), _connector='OR'), name='catalog_product_package_quantity_positive'),
        ),
    ]
