// Static preview of the merge screens for the human reviewer: the real view components rendered in Node
// (React server markup) from the answers of a running QA server. No browser is started and nothing is
// clicked, so the pages are not interactive and do not replace the manual acceptance in a browser.
//
// Usage, from the repository root with the QA environment of ACCEPTANCE.md applied:
//   node frontend/src/features/merges/preview/render.mjs <vite-origin> pending    # fresh demo database
//   node frontend/src/features/merges/preview/render.mjs <vite-origin> resolved   # after the proxy check
import assert from 'node:assert/strict'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { createElement as h } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { createServer } from 'vite'

const [originArgument, stage] = process.argv.slice(2)
assert.ok(originArgument && ['pending', 'resolved'].includes(stage), 'Usage: render.mjs <vite-origin> pending|resolved')
const origin = new URL(originArgument)
assert.ok(['127.0.0.1', 'localhost'].includes(origin.hostname) && !['8000', '5173'].includes(origin.port), 'Use the loopback QA Vite origin, never dev')
const out = new URL('./', import.meta.url)
const source = new URL('../../../', import.meta.url)
const options = { baseUrl: `${origin.origin}/api` }
const loader = await createServer({ root: fileURLToPath(new URL('../../../../', import.meta.url)), server: { middlewareMode: true, hmr: false }, appType: 'custom', logLevel: 'error' })

try {
  const load = (path) => loader.ssrLoadModule(path)
  const api = await load('/src/api/product-merges.ts')
  const catalog = await load('/src/api/catalog.ts')
  const { MergesView } = await load('/src/features/merges/MergesPage.tsx')
  const { MergeSummary } = await load('/src/features/merges/MergePage.tsx')
  const { default: MergeGroupView } = await load('/src/features/merges/MergeGroupView.tsx')
  const { default: MergeLines } = await load('/src/features/merges/MergeLines.tsx')
  const marks = await load('/src/features/merges/MergeMarks.tsx')
  const state = await load('/src/features/merges/state.ts')
  const { default: ProductList } = await load('/src/features/catalog/ProductList.tsx')
  const ok = (result) => { assert.equal(result.kind, 'ok', JSON.stringify(result)); return result.data }
  const noop = () => {}
  const loaded = (data) => ({ kind: 'ok', data, refreshing: false })
  const written = []

  const css = ['App.css', 'features/merges/Merges.css', 'features/catalog/Catalog.css', 'features/product/Product.css']
    .map((path) => `/* ${path} */\n${readFileSync(new URL(path, source), 'utf8')}`).join('\n')
  writeFileSync(new URL('preview.css', out), `/* Generated by render.mjs from the application styles. Do not edit. */\n${css}\n.preview-note { margin: 16px 0 0; padding: 12px 14px; border: 1px dashed #8b9c8d; border-radius: 8px; color: #40564a; font-size: 0.85rem; }\n`)

  const page = (file, title, note, content) => {
    const html = `<!doctype html>\n<html lang="ru">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Checkist — ${title}</title>\n<link rel="stylesheet" href="./preview.css">\n</head>\n<body>\n<div class="page">\n<p class="preview-note">Статическая отрисовка настоящих компонентов экрана на ответах QA-сервера (демо-данные). Ссылки и кнопки здесь не работают: ${note}</p>\n<main><div class="intro"><h1>${title}</h1></div>\n${renderToStaticMarkup(content)}\n</main>\n</div>\n</body>\n</html>\n`
    writeFileSync(new URL(file, out), html)
    written.push(file)
  }
  const idle = { kind: 'idle' }
  const listPage = (file, query, data, note) => page(file, 'Дубли товаров', note,
    h(MergesView, { query, state: loaded(data), action: idle, onDetect: noop, onRetry: noop }))
  const groupPage = async (file, id, note, choose = (group) => state.initialSelection(group)) => {
    const group = ok(await api.getProductMerge(id, options))
    const lines = ok(await api.getProductMergeLines(id, {}, options))
    page(file, 'Группа дублей', note, h('div', { className: 'ck-merge' },
      h('section', { className: 'ck-merge-panel' }, h('h2', null, `Группа №${group.id}`), h(MergeSummary, { group })),
      h(MergeGroupView, { group, selection: state.normalizeSelection(group, choose(group)), action: idle, onSelection: noop, onConfirm: noop, onCancel: noop, onExclude: noop }),
      h('section', { className: 'ck-merge-panel' }, h('h2', null, 'Покупки группы'), h(MergeLines, { group, lines, onPage: noop }))))
    return group
  }
  const hintPage = (file, hint, note) => page(file, 'Товар и история цен', note, h('div', { className: 'product-page' },
    h('section', { className: 'product-panel' }, h('h2', null, 'Товар объединён'), h(marks.MergedProductHint, { hint }))))
  const all = ok(await api.getProductMerges({ page_size: 200 }, options))

  if (stage === 'pending') {
    const pending = ok(await api.getProductMerges({ status: 'pending' }, options))
    assert.ok(pending.results.length > 0, 'No pending groups: use a fresh demo database')
    listPage('list-pending.html', { page: 1 }, pending, 'список ожидающих групп, `/catalog/merges`.')
    const plain = pending.results.filter((group) => !group.has_conflicts).sort((a, b) => b.members.length - a.members.length || a.id - b.id)[0]
    const disputed = pending.results.find((group) => group.has_conflicts)
    assert.ok(plain && disputed, 'The demo must contain a plain and a conflicting pending group')
    await groupPage('group-pending.html', plain.id, `ожидающая группа без конфликта, \`/catalog/merges/${plain.id}\`, выбор по умолчанию.`)
    await groupPage('group-conflict.html', disputed.id, `группа с конфликтом, \`/catalog/merges/${disputed.id}\`: значение не выбрано, подтверждение недоступно.`)
    const kept = ok(await catalog.getProduct(plain.target_product_id, options))
    const q = /pizza/i.test(kept.name) ? 'pizza' : kept.name.slice(0, 5)
    const found = ok(await catalog.getProducts({ q }, options))
    page('catalog-marks.html', 'Каталог продуктов', `список каталога по запросу «${q}» со значком у оставляемого товара.`, h('div', { className: 'ck-catalog' },
      h('section', { className: 'ck-catalog-results' }, h('h2', null, 'Результаты поиска'), h(ProductList, { products: found.results, merges: state.pendingTargets(pending.results) }))))
    page('product-notice.html', 'Товар и история цен', `пометка в карточке оставляемого товара, \`/catalog/products/${kept.id}\` (остальные блоки карточки не показаны).`, h('div', { className: 'product-page' },
      h('section', { className: 'product-panel' }, h('h2', null, kept.name), h(marks.ProductMergeNotice, { mark: state.pendingTargets(pending.results).get(kept.id) }))))
    const absorbed = plain.members.find((member) => member.role === 'source').product_id
    assert.deepEqual(await catalog.getProduct(absorbed, options), { kind: 'error', reason: 'not_found', status: 404 })
    hintPage('product-merged-pending.html', state.mergedHint(ok(await api.getProductMerges({ product: absorbed }, options)).results, absorbed),
      `подсказка вместо «Товар не найден» для поглощённой записи, \`/catalog/products/${absorbed}\`, пока группа ожидает.`)
  } else {
    listPage('list-all.html', { status: 'all', page: 1 }, all, 'все группы после подтверждений, отмены и исключения, `/catalog/merges?status=all`.')
    const confirmed = all.results.find((group) => group.status === 'confirmed')
    const cancelled = all.results.find((group) => group.status === 'cancelled')
    assert.ok(confirmed && cancelled, 'Run the proxy check first: it confirms and cancels groups')
    await groupPage('group-confirmed.html', confirmed.id, `итог после подтверждения, \`/catalog/merges/${confirmed.id}\`: действий нет.`)
    await groupPage('group-cancelled.html', cancelled.id, `итог после отмены, \`/catalog/merges/${cancelled.id}\`: покупки возвращены исходным товарам.`)
    const deleted = confirmed.members.find((member) => !member.exists).product_id
    assert.deepEqual(await catalog.getProduct(deleted, options), { kind: 'error', reason: 'not_found', status: 404 })
    hintPage('product-merged-confirmed.html', state.mergedHint(ok(await api.getProductMerges({ product: deleted }, options)).results, deleted),
      `подсказка для удалённой при подтверждении записи, \`/catalog/products/${deleted}\`.`)
  }
  console.log(`Merge preview (${stage}) written: ${written.join(', ')}`)
} catch (error) {
  console.error(`Merge preview FAILED: ${error instanceof Error ? error.message : error}`)
  process.exitCode = 1
} finally {
  await loader.close()
}
