# Generated by Django 5.2.17 on 2026-10-03 12:33

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0002_seed_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('sale', 'Продажа'), ('refund', 'Возврат')], max_length=8)),
                ('purchased_at', models.DateTimeField()),
                ('purchased_on', models.DateField()),
                ('receipt_number', models.CharField(blank=True, default='', max_length=64)),
                ('shift_number', models.CharField(blank=True, default='', max_length=16)),
                ('register_code', models.CharField(blank=True, default='', max_length=64)),
                ('fiscal_key', models.CharField(blank=True, default='', max_length=160)),
                ('fiscal', models.JSONField(blank=True, default=dict)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('prices_include_tax', models.BooleanField(default=True)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='stores.currency')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга'), ('deposit', 'Залог'), ('deposit_return', 'Возврат тары')], max_length=16)),
                ('raw_name', models.TextField()),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('store_item_code', models.CharField(blank=True, default='', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('g', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л'), ('m', 'м')], default='pcs', max_length=8)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_code', models.CharField(blank=True, default='', max_length=8)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_excise', models.BooleanField(default=False)),
                ('is_marked', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='receipts.receiptline')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='catalog.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receipts.receipt')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='stores.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='receipts.receipt')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='receipts.receiptline')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(blank=True, default='', max_length=8)),
                ('net', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='receipts.receipt')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_taxes', to='stores.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=255)),
                ('store_item_code', models.CharField(blank=True, default='', max_length=64)),
                ('raw_name', models.TextField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_aliases', to='stores.merchant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'product aliases',
                'constraints': [models.UniqueConstraint(fields=('merchant', 'name_key', 'store_item_code'), name='receipts_productalias_merchant_name_code_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['store', 'purchased_at'], name='receipts_rcpt_store_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('fiscal_key', ''), _negated=True), fields=('fiscal_key',), name='receipts_receipt_fiscal_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_number', ''), _negated=True), fields=('store', 'purchased_on', 'shift_number', 'register_code', 'receipt_number'), name='receipts_receipt_store_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('fiscal_key', ''), ('receipt_number', '')), fields=('store', 'purchased_at', 'total'), name='receipts_receipt_store_time_total_uniq'),
        ),
        migrations.AddIndex(
            model_name='receiptline',
            index=models.Index(fields=['product', 'receipt'], name='receipts_line_prod_rcpt_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptline',
            index=models.Index(fields=['store_item_code'], name='receipts_line_item_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'position'), name='receipts_receiptline_receipt_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='receipts_receiptline_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='receipts_receiptline_discount_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='receipts_receiptline_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gte', 0), ('quantity__gte', 0)), models.Q(('amount__lte', 0), ('quantity__lte', 0)), _connector='OR'), name='receipts_receiptline_quantity_amount_same_sign'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'deposit_return'), _negated=True), ('amount__lte', 0), _connector='OR'), name='receipts_receiptline_deposit_return_not_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), ('kind', 'deposit'), _connector='OR'), name='receipts_receiptline_parent_only_for_deposit'),
        ),
        migrations.AddConstraint(
            model_name='receiptdiscount',
            constraint=models.UniqueConstraint(fields=('receipt', 'position'), name='receipts_receiptdiscount_receipt_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiptdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receipts_receiptdiscount_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipttax',
            constraint=models.UniqueConstraint(fields=('receipt', 'tax_rate'), name='receipts_receipttax_receipt_tax_rate_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receipttax',
            constraint=models.CheckConstraint(condition=models.Q(('gross', django.db.models.expressions.CombinedExpression(models.F('net'), '+', models.F('tax')))), name='receipts_receipttax_net_plus_tax_eq_gross'),
        ),
    ]
