// Static preview of the classification screen and its marks for the human reviewer: the real view components
// rendered in Node (React server markup) from the answers of a running QA server. No browser is started and
// nothing is clicked, so the pages are not interactive and do not replace the manual acceptance in a browser.
// Every stage also checks the two requests of the marks through the real adapters and the Vite proxy.
//
// Usage, from the repository root with the QA environment of ACCEPTANCE.md applied:
//   node frontend/src/features/classification/preview/render.mjs <vite-origin> pending    # fresh demo database
//   node frontend/src/features/classification/preview/render.mjs <vite-origin> resolved   # after the proxy check
//   node frontend/src/features/classification/preview/render.mjs <vite-origin> off        # ALLOW_LOCAL_RECOGNITION_API=0, writes nothing
import assert from 'node:assert/strict'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { createElement as h } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { createServer } from 'vite'

const [originArgument, stage] = process.argv.slice(2)
assert.ok(originArgument && ['pending', 'resolved', 'off'].includes(stage), 'Usage: render.mjs <vite-origin> pending|resolved|off')
const origin = new URL(originArgument)
assert.ok(['127.0.0.1', 'localhost'].includes(origin.hostname) && !['8000', '5173'].includes(origin.port), 'Use the loopback QA Vite origin, never dev')
const out = new URL('./', import.meta.url)
const source = new URL('../../../', import.meta.url)
const options = { baseUrl: `${origin.origin}/api` }
const loader = await createServer({ root: fileURLToPath(new URL('../../../../', import.meta.url)), server: { middlewareMode: true, hmr: false }, appType: 'custom', logLevel: 'error' })

try {
  const load = (path) => loader.ssrLoadModule(path)
  const api = await load('/src/api/product-classifications.ts')
  const catalog = await load('/src/api/catalog.ts')
  const { ClassificationView } = await load('/src/features/classification/ClassificationPage.tsx')
  const { GenericChooserView, chooserPageSize } = await load('/src/features/classification/GenericChooser.tsx')
  const marks = await load('/src/features/classification/marks.ts')
  const views = await load('/src/features/classification/ClassificationMarks.tsx')
  const state = await load('/src/features/classification/state.ts')
  const { default: ProductList } = await load('/src/features/catalog/ProductList.tsx')
  const ok = (result) => { assert.equal(result.kind, 'ok', JSON.stringify(result)); return result.data }
  const noop = () => {}
  const loaded = (data) => ({ kind: 'ok', data, refreshing: false })
  const idle = { kind: 'idle' }
  const written = []
  // Exactly the requests of the catalog list and of the product card.
  const listMarks = () => api.getProductClassifications({ status: 'pending', page_size: 200 }, options)
  const cardMarks = (product) => api.getProductClassifications({ product, status: 'pending' }, options)
  const products = ok(await catalog.getProducts({ page_size: 200 }, options))
  assert.ok(products.results.length > 0, 'The catalog is empty: seed the demo first')

  if (stage === 'off') {
    const refused = { kind: 'error', reason: 'permission_denied', status: 403 }
    assert.deepEqual(await listMarks(), refused)
    assert.deepEqual(await cardMarks(products.results[0].id), refused)
    assert.deepEqual(await api.getProductClassificationState(options), refused)
    assert.equal(marks.marksOf({ kind: 'error', error: refused }).size, 0)
    ok(await catalog.getProduct(products.results[0].id, options))
    console.log(`Classification marks with the local API off: both mark requests 403 permission_denied, no marks; catalog (${products.results.length} products) and the card answer 200`)
  } else {
    const css = ['App.css', 'features/classification/Classification.css', 'features/merges/Merges.css', 'features/catalog/Catalog.css', 'features/product/Product.css']
      .map((path) => `/* ${path} */\n${readFileSync(new URL(path, source), 'utf8')}`).join('\n')
    writeFileSync(new URL('preview.css', out), `/* Generated by render.mjs from the application styles. Do not edit. */\n${css}\n.preview-note { margin: 16px 0 0; padding: 12px 14px; border: 1px dashed #8b9c8d; border-radius: 8px; color: #40564a; font-size: 0.85rem; }\n`)
    const page = (file, title, note, content) => {
      const html = `<!doctype html>\n<html lang="ru">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Checkist — ${title}</title>\n<link rel="stylesheet" href="./preview.css">\n</head>\n<body>\n<div class="page">\n<p class="preview-note">Статическая отрисовка настоящих компонентов экрана на ответах QA-сервера (демо-данные). Ссылки и кнопки здесь не работают: ${note}</p>\n<main><div class="intro"><h1>${title}</h1></div>\n${renderToStaticMarkup(content)}\n</main>\n</div>\n</body>\n</html>\n`
      writeFileSync(new URL(file, out), html)
      written.push(file)
    }
    const status = ok(await api.getProductClassificationState(options))
    const screen = (file, query, list, note, open) => page(file, 'Категории товаров', note, h(ClassificationView, {
      query, state: loaded(status), list: loaded(list), action: idle, open,
      onRun: noop, onRetryAction: noop, onRetryState: noop, onRetryList: noop, onAction: noop, onOpen: noop, onClose: noop,
    }))
    const pending = ok(await listMarks())
    const found = marks.pendingMarks(pending.results)
    const shown = products.results.filter((product) => marks.markFor(found, product))
    // A pending record always has a live product that still carries the suggested generic product.
    assert.equal(shown.length, pending.count, 'Every pending record must mark exactly one catalog product')
    const catalogPage = (file, note) => page(file, 'Каталог продуктов', note, h('div', { className: 'ck-catalog' },
      h('section', { className: 'ck-catalog-results' }, h('h2', null, 'Все товары'), h(ProductList, { products: products.results, classifications: found }))))

    if (stage === 'pending') {
      assert.ok(pending.count > 0, 'No pending records: use a fresh demo database with applied suggestions')
      const list = ok(await api.getProductClassifications(state.listParams({ page: 1 }), options))
      screen('screen-pending.html', { page: 1 }, list, `ожидающие записи группами, \`/catalog/classification\`: ${pending.count} записей, без категории ${status.unclassified_count}.`)
      // The record with a category created by the mechanism shows «новая» in every place.
      const fresh = list.results.find((record) => record.suggested.category?.path.some((item) => item.is_new)) ?? list.results[0]
      const group = list.results.find((record) => record.suggested.pending_count > 1) ?? fresh
      screen('screen-confirm-all.html', { page: 1 }, list, `то же, открыто подтверждение группы «${group.suggested.generic.name}» («Подтвердить все»).`, { kind: 'bulk', genericId: group.suggested.generic.id })
      screen('screen-reject.html', { page: 1 }, list, `то же, открыто подтверждение отклонения записи «${fresh.product.name}».`, { kind: 'reject', id: fresh.id })
      const own = ok(await cardMarks(fresh.product.id))
      assert.deepEqual(own.results.map((record) => record.id), [fresh.id])
      screen('screen-product.html', { product: fresh.product.id, page: 1 }, ok(await api.getProductClassifications(state.listParams({ product: fresh.product.id, page: 1 }), options)),
        `записи одного товара, \`/catalog/classification?product=${fresh.product.id}\` — сюда ведут значок каталога и ссылка карточки.`)
      const generics = ok(await catalog.getGenericProducts({ page_size: chooserPageSize }, options))
      const options_ = state.chooseOptions(generics.results, fresh)
      page('screen-choose.html', 'Категории товаров', `область «Выбрать другой» для записи «${fresh.product.name}» со списком обобщённых продуктов каталога, выбран первый вариант (остальной экран не показан).`,
        h('div', { className: 'ck-class' }, h('section', { className: 'ck-class-panel' }, h(GenericChooserView, {
          record: fresh, text: '', state: loaded(generics), selected: options_[0]?.id, busy: false, saving: false,
          onText: noop, onSelect: noop, onApply: noop, onCancel: noop, onRetry: noop,
        }))))
      catalogPage('catalog-marks.html', `список каталога со значком у ${shown.length} из ${products.results.length} товаров.`)
      const card = ok(await catalog.getProduct(fresh.product.id, options))
      const mark = marks.markFor(marks.marksOf(loaded(own)), card)
      assert.ok(mark, 'The card of the product must get its notice')
      page('product-notice.html', 'Товар и история цен', `пометка в карточке товара, \`/catalog/products/${card.id}\` (остальные блоки карточки не показаны).`, h('div', { className: 'product-page' },
        h('section', { className: 'product-panel' }, h('h2', null, card.name), h(views.ProductClassificationNotice, { mark }))))
    } else {
      const all = ok(await api.getProductClassifications(state.listParams({ status: 'all', page: 1 }), options))
      assert.ok(all.results.some((record) => record.status === 'confirmed') && all.results.some((record) => record.status === 'rejected'), 'Run the proxy check first: it confirms and rejects records')
      screen('screen-all.html', { status: 'all', page: 1 }, all, 'все записи после подтверждений, выбора другого и отклонений, `/catalog/classification?status=all`; запуск в очереди без воркера.')
      screen('screen-pending-after.html', { page: 1 }, ok(await api.getProductClassifications(state.listParams({ page: 1 }), options)), 'оставшиеся ожидающие записи после решений, `/catalog/classification`.')
      catalogPage('catalog-marks-after.html', `каталог после решений: значок остался у ${shown.length} из ${products.results.length} товаров.`)
      // A decided product keeps its card and loses the notice.
      const decided = all.results.find((record) => record.status === 'confirmed' && record.product.exists)
      assert.equal(ok(await cardMarks(decided.product.id)).count, 0)
    }
    console.log(`Classification preview (${stage}) written: ${written.join(', ')}; marks: ${shown.length} of ${products.results.length} products`)
  }
} catch (error) {
  console.error(`Classification preview FAILED: ${error instanceof Error ? error.message : error}`)
  process.exitCode = 1
} finally {
  await loader.close()
}
