# Generated by Django 5.2.17 on 2026-10-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, default='', max_length=100)),
                ('tax_id_type', models.CharField(blank=True, choices=[('inn', 'ИНН'), ('bin', 'БИН'), ('vat_id', 'VAT ID'), ('other', 'Другое')], default='', max_length=16)),
                ('tax_id', models.CharField(blank=True, default='', max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='stores.country')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('branch_code', models.CharField(blank=True, default='', max_length=32)),
                ('address_raw', models.TextField()),
                ('address_i18n', models.JSONField(blank=True, default=dict)),
                ('address_key', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=16)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('house', models.CharField(blank=True, default='', max_length=32)),
                ('timezone', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.country')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vat', 'НДС'), ('exempt', 'Без НДС')], max_length=16)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('name', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='stores.country')),
            ],
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('country', 'tax_id'), name='stores_merchant_country_tax_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('merchant', 'address_key'), name='stores_store_merchant_address_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(condition=models.Q(('branch_code', ''), _negated=True), fields=('merchant', 'branch_code'), name='stores_store_merchant_branch_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(fields=('country', 'kind', 'rate'), name='stores_taxrate_country_kind_rate_uniq', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'exempt'), ('rate__isnull', True)), models.Q(('kind', 'vat'), ('rate__gte', 0), ('rate__isnull', False)), _connector='OR'), name='stores_taxrate_kind_rate_check'),
        ),
    ]
