# Generated by Django 5.2.17 on 2026-10-04 20:21

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.lookups
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('succeeded', 'Succeeded'), ('partial_succeeded', 'Partial Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('stage', models.CharField(choices=[('waiting', 'Waiting'), ('prepare', 'Prepare'), ('detect', 'Detect'), ('crop', 'Crop'), ('recognize', 'Recognize'), ('validate', 'Validate'), ('import', 'Import'), ('finished', 'Finished')], default='waiting', max_length=16)),
                ('detected_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_count', models.PositiveSmallIntegerField(default=0)),
                ('imported_count', models.PositiveSmallIntegerField(default=0)),
                ('reused_count', models.PositiveSmallIntegerField(default=0)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('failed_count', models.PositiveSmallIntegerField(default=0)),
                ('cancelled_count', models.PositiveSmallIntegerField(default=0)),
                ('current_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('run_token', models.UUIDField(blank=True, null=True)),
                ('claim_count', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processing_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='recognition.processingjob')),
            ],
        ),
        migrations.CreateModel(
            name='SourcePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_file', models.FileField(max_length=255, upload_to='')),
                ('upright_file', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('sha256', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Expected a lowercase SHA-256 digest.')])),
                ('content_type', models.CharField(max_length=16)),
                ('bytes', models.PositiveIntegerField()),
                ('raw_width', models.PositiveIntegerField()),
                ('raw_height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('exif_orientation', models.PositiveSmallIntegerField(default=1)),
                ('preparation_version', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'id'], name='rec_photo_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('bytes__gt', 0), ('bytes__lte', 20971520)), name='rec_photo_bytes_check'), models.CheckConstraint(condition=models.Q(('height__gt', 0), ('raw_height__gt', 0), ('raw_width__gt', 0), ('width__gt', 0), django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(models.F('raw_width'), models.BigIntegerField()), '*', models.F('raw_height')), 40000000), django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(models.F('width'), models.BigIntegerField()), '*', models.F('height')), 40000000)), name='rec_photo_pixels_check'), models.CheckConstraint(condition=models.Q(('exif_orientation__gte', 1), ('exif_orientation__lte', 8)), name='rec_photo_orientation_check'), models.CheckConstraint(condition=models.Q(('content_type__in', ['image/jpeg', 'image/png', 'image/webp'])), name='rec_photo_type_check')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('file', models.FileField(max_length=255, upload_to='')),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Expected a lowercase SHA-256 digest.')])),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('bbox', models.JSONField()),
                ('quad', models.JSONField(blank=True, null=True)),
                ('rotation_degrees', models.FloatField(default=0)),
                ('crop_transform', models.JSONField(blank=True, default=dict)),
                ('clipped', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('imported', 'Imported'), ('reused', 'Reused'), ('updated', 'Updated'), ('needs_review', 'Needs Review'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('import_effect', models.CharField(choices=[('none', 'None'), ('created', 'Created'), ('linked', 'Linked'), ('updated', 'Updated')], default='none', max_length=8)),
                ('normalized_result', models.JSONField(blank=True, null=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('outcome_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recognition.processingjob')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_images', to='receipts.receipt')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_images', to='recognition.sourcephoto')),
            ],
        ),
        migrations.AddField(
            model_name='processingjob',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='recognition.sourcephoto'),
        ),
        migrations.CreateModel(
            name='RecognitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('detect', 'Detect'), ('recognize', 'Recognize')], max_length=10)),
                ('ordinal', models.PositiveSmallIntegerField(default=1)),
                ('run_token', models.UUIDField()),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('cli_version', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('schema_version', models.CharField(max_length=64)),
                ('input_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Expected a lowercase SHA-256 digest.')])),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('invalid_output_text', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='recognition.receiptimage')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='recognition.processingjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'id'], name='rec_attempt_job_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'phase', 'image', 'ordinal'), name='rec_attempt_ordinal_uniq', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='rec_attempt_ordinal_check'), models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', True), ('phase', 'detect')), models.Q(('image__isnull', False), ('phase', 'recognize')), _connector='OR'), name='rec_attempt_phase_check'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'running')), models.Q(('finished_at__isnull', False), ('status__in', ['succeeded', 'failed', 'cancelled'])), _connector='OR'), name='rec_attempt_finished_check')],
            },
        ),
        migrations.AddIndex(
            model_name='receiptimage',
            index=models.Index(fields=['photo', 'id'], name='rec_image_photo_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptimage',
            index=models.Index(fields=['receipt', 'id'], name='rec_image_receipt_idx'),
        ),
        migrations.AddConstraint(
            model_name='receiptimage',
            constraint=models.UniqueConstraint(fields=('job', 'position'), name='rec_image_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiptimage',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 10)), name='rec_image_position_check'),
        ),
        migrations.AddConstraint(
            model_name='receiptimage',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0), ('width__gt', 0), django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(models.F('width'), models.BigIntegerField()), '*', models.F('height')), 40000000)), name='rec_image_pixels_check'),
        ),
        migrations.AddConstraint(
            model_name='receiptimage',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'imported', 'reused', 'updated', 'needs_review', 'failed', 'cancelled'])), name='rec_image_status_check'),
        ),
        migrations.AddConstraint(
            model_name='receiptimage',
            constraint=models.CheckConstraint(condition=models.Q(('import_effect__in', ['none', 'created', 'linked', 'updated'])), name='rec_image_effect_check'),
        ),
        migrations.AddConstraint(
            model_name='receiptimage',
            constraint=models.CheckConstraint(condition=models.Q(('rotation_degrees__gte', -180), ('rotation_degrees__lte', 180)), name='rec_image_rotation_check'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'available_at', 'id'], name='rec_job_available_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='rec_job_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running', 'cancel_requested'))), fields=('photo',), name='rec_job_active_photo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'cancel_requested', 'cancelled', 'succeeded', 'partial_succeeded', 'failed'])), name='rec_job_status_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['waiting', 'prepare', 'detect', 'crop', 'recognize', 'validate', 'import', 'finished'])), name='rec_job_stage_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='rec_job_version_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('detected_count__isnull', True), ('detected_count__lte', 10), _connector='OR'), name='rec_job_detected_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('current_position__isnull', True), models.Q(('current_position__gte', 1), ('current_position__lte', models.F('detected_count')), ('detected_count__isnull', False)), _connector='OR'), name='rec_job_position_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', False), ('stage', 'finished'), ('status__in', ('cancelled', 'succeeded', 'partial_succeeded', 'failed'))), models.Q(('finished_at__isnull', True), ('status__in', ('queued', 'running', 'cancel_requested')), models.Q(('stage', 'finished'), _negated=True)), _connector='OR'), name='rec_job_finished_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('heartbeat_at__isnull', False), ('lease_expires_at__isnull', False), ('processing_deadline_at__isnull', False), ('run_token__isnull', False), ('started_at__isnull', False), ('status__in', ('running', 'cancel_requested'))), models.Q(('heartbeat_at__isnull', True), ('lease_expires_at__isnull', True), ('run_token__isnull', True), ('status__in', ['queued', 'cancelled', 'succeeded', 'partial_succeeded', 'failed'])), _connector='OR'), name='rec_job_ownership_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancel_requested_at__isnull', False), ('status__in', ['cancel_requested', 'cancelled'])), models.Q(models.Q(('status__in', ['cancel_requested', 'cancelled']), _negated=True), ('cancel_requested_at__isnull', True)), _connector='OR'), name='rec_job_cancel_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('completed_count__lte', 10), models.Q(models.Q(('completed_count', 0), ('detected_count__isnull', True)), models.Q(('completed_count__lte', models.F('detected_count')), ('detected_count__isnull', False)), _connector='OR')), name='rec_job_completed_count_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('imported_count__lte', 10), models.Q(models.Q(('detected_count__isnull', True), ('imported_count', 0)), models.Q(('detected_count__isnull', False), ('imported_count__lte', models.F('detected_count'))), _connector='OR')), name='rec_job_imported_count_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('reused_count__lte', 10), models.Q(models.Q(('detected_count__isnull', True), ('reused_count', 0)), models.Q(('detected_count__isnull', False), ('reused_count__lte', models.F('detected_count'))), _connector='OR')), name='rec_job_reused_count_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('review_count__lte', 10), models.Q(models.Q(('detected_count__isnull', True), ('review_count', 0)), models.Q(('detected_count__isnull', False), ('review_count__lte', models.F('detected_count'))), _connector='OR')), name='rec_job_review_count_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('failed_count__lte', 10), models.Q(models.Q(('detected_count__isnull', True), ('failed_count', 0)), models.Q(('detected_count__isnull', False), ('failed_count__lte', models.F('detected_count'))), _connector='OR')), name='rec_job_failed_count_check'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_count__lte', 10), models.Q(models.Q(('cancelled_count', 0), ('detected_count__isnull', True)), models.Q(('cancelled_count__lte', models.F('detected_count')), ('detected_count__isnull', False)), _connector='OR')), name='rec_job_cancelled_count_check'),
        ),
    ]
