# Generated by Django 5.2.17 on 2026-10-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('target_ref', models.BigIntegerField()),
                ('detector_version', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'id'], name='merges_merge_status_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'pending')), models.Q(('status__in', ['confirmed', 'cancelled']), ('resolved_at__isnull', False)), _connector='OR'), name='merges_productmerge_pending_unresolved')],
            },
        ),
        migrations.CreateModel(
            name='ProductMergeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ref', models.BigIntegerField()),
                ('role', models.CharField(choices=[('target', 'Оставляемая'), ('source', 'Поглощаемая')], max_length=8)),
                ('state', models.CharField(choices=[('active', 'В группе'), ('excluded', 'Исключена')], default='active', max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('active_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_merge_member', to='catalog.product')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='merges.productmerge')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMergeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_entries', to='receipts.receiptline')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='merges.productmergemember')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMergeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_entries', to='receipts.productalias')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='merges.productmergemember')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMergeRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to='merges.productmerge')),
                ('product_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('product_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productmergemember',
            constraint=models.UniqueConstraint(fields=('group', 'product_ref'), name='merges_member_group_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productmergemember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'target'), ('state', 'active')), fields=('group',), name='merges_member_group_target_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productmergeline',
            constraint=models.UniqueConstraint(fields=('member', 'line'), name='merges_line_member_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productmergealias',
            constraint=models.UniqueConstraint(fields=('member', 'alias'), name='merges_alias_member_alias_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productmergerejection',
            constraint=models.UniqueConstraint(fields=('product_low', 'product_high'), name='merges_rejection_pair_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productmergerejection',
            constraint=models.CheckConstraint(condition=models.Q(('product_low__lt', models.F('product_high'))), name='merges_rejection_low_lt_high'),
        ),
    ]
